name = "highermind"
compatibility_date = "2024-04-03"

[site]
bucket = "./video_particles"

[build]
command = ""

[functions]
directory = "functions"

[[routes]]
pattern = "/api/videos"
function = "api/videos"

[[routes]]
pattern = "/api/browse"
function = "api/browse"

[[routes]]
pattern = "/api/browse-config"
function = "api/browse-config"
