name = "highermind"
compatibility_date = "2024-04-03"

[site]
bucket = "video_particles"

[[routes]]
pattern = "/api/videos"
script = "api/videos"

[[routes]]
pattern = "/api/browse"
script = "api/browse" 