[build]
command = "echo 'No build step required'"
output_dir = "video_particles"

[site]
bucket = "video_particles"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[functions]
directory = "functions"

[[routes]]
pattern = "/api/browse"
script = "api/browse.js"

[[routes]]
pattern = "/api/videos"
script = "api/videos.js" 