name = "highermind"
compatibility_date = "2024-04-03"

[site]
bucket = "./video_particles"

[build]
command = ""
upload.format = "service-worker"

[[routes]]
pattern = "/api/videos/*"

[[routes]]
pattern = "/api/browse/*"
