name = "highermind"
compatibility_date = "2024-04-03"
main = "workers-site/index.js"

[site]
bucket = "video_particles"

[build]
command = ""

[[routes]]
pattern = "/api/videos"
script = "api/videos"

[[routes]]
pattern = "/api/browse"
script = "api/browse"
