name = "highermind"
compatibility_date = "2024-04-03"

[build]
command = ""
upload.format = "directory"
dir = "video_particles"

[[redirects]]
from = "/api/videos"
to = "/api/videos"
status = 200

[[redirects]]
from = "/api/browse"
to = "/api/browse"
status = 200 